---
deployment:
  task:
    - export DEPLOYPATH=/home/libremyi/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp -R style $DEPLOYPATH
    - /bin/cp -R script $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R mc.libre.my.id $DEPLOYPATH
